mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

app_name='myapp'
urlpatterns = [
   
    path('index/',views.index,name="index"),
    path('book/<int:book_id>/',views.detail,name="detail"),
    path('add/',views.add_book,name="add_book"),
    path('update/<int:id>/',views.update,name="update"),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('add_task/',views.add,name='add_task')
   
]


mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views,urls
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls"))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Book(models.Model):
    def __str__(self):
        return "{0}".format(self.name)
    name=models.CharField(max_length=100)
    desc=models.CharField(max_length=300)
    price=models.IntegerField()
    book_image=models.ImageField(default='default.jpg',upload_to='book_images/')

class Task(models.Model):
    def __str__(self):
        return "{0}".format(self.name)
    name=models.CharField(max_length=100, default='')
    desc=models.CharField(max_length=300, default='')
    start_date = models.DateField(default=datetime.date.today)
    end_date = models.DateField(default=datetime.date.today)
    start_time = models.TimeField(default=timezone.now().time())
    end_time = models.TimeField(default=timezone.now().time())

mysite/myapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model=Book
        fields=['name','desc','book_image','price','book_image']

mysite/myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse 
from .models import Book, Task
from .forms import BookForm

# Create your views here.
def index(req):
    book_list=Book.objects.all()
    context={
        "book_list":book_list
    }
    return render(req,'myapp/index.html',context)

def detail(req,book_id):
    book=Book.objects.get(id=book_id)
    return render(req,"myapp/detail.html",{"book":book})

def add_book(req):
    if req.method=="POST":
        name=req.POST.get('name',)
        desc=req.POST.get('desc',)
        price=req.POST.get('price',)
        book_image=req.FILES['book_image']

        book=Book(name=name,desc=desc,price=price,book_image=book_image)
        book.save()
    return render(req,'myapp/add_book.html')

def update(req,id):
    book=Book.objects.get(id=id)
    form=BookForm(req.POST or None,req.FILES,instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(req,'myapp/edit.html',{"form":form,'book':book})

def delete(req,id):
    if req.method=="POST":
        book=Book.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(req,'myapp/delete.html')

def add(req):
    if req.method=="POST":
        name=req.POST.get('name',)
        desc=req.POST.get('desc',)
        start_date=req.POST.get('start_date',)
        end_date=req.POST.get('end_date',)
        start_time=req.POST.get('start_time','')
        end_time=req.POST.get('end_time','')
        book=Task(name=name,desc=desc,start_date=start_date,end_date=end_date,start_time=start_time,end_time=end_time)
        book.save()
    return render(req,'myapp/add.html')

mysite/myapp/templates/myapp/add.html
{% extends './base.html'%}
{%block body%}
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <input type="text" name="name" id="name" placeholder="enter boook name"><br>
    <input type="text" name="desc" id="desc" placeholder="enter boook desc"><br>
    <input type="date" name="start_date" placeholder="start date"><br>
    <input type="date" name="end_date" placeholder="end date"><br>
    <input type="time" name="start_time"><br>
    <input type="time" name="end_time"><br>
    <input type="submit">
</form>
{%endblock%}

mysite/myapp/templates/myapp/add_book.html
{%extends './base.html'%}

{%block body%}
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <input type="text" name="name" id="name" placeholder="enter boook name"><br>
    <input type="text" name="desc" id="desc" placeholder="enter boook desc"><br>
    <input type="text" name="price" id="price" placeholder="enter boook price"><br>
    <input type="file" name="book_image" id="book_image" placeholder="enter boook image"><br>
    <input type="submit">
</form>
{%endblock%}

mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static  'myapp/style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand">Book Store</a>
    </nav>


    {% block body%}

    {%endblock%}

</body>
</html>

mysite/myapp/templates/myapp/delete.html
<form method="POST">
    {%csrf_token%}
    Are you sure to delete this book.
    <input type="submit">
</form>

mysite/myapp/templates/myapp/detail.html
{%extends 'myapp/base.html'%}

    {% block body%}
    <h1>{{book.name}}</h1>
    <img width=100 height=100 src="{{book.book_image.url}}" alt="">
    <p>{{book.desc}}<br>
        {{book.price}}
    </p>
    <a class="btn btn-secondary" href="{%url 'myapp:update' book.id%}">edit</a>
    <a class="btn btn-danger" href="{%url 'myapp:delete' book.id%}">delete</a>
    {%endblock%}

mysite/myapp/templates/myapp/edit.html
<form method="POST" ectype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit">
</form>

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html'%}

    {%block body%}
    {%for book in book_list%}
    <a href="{%url 'myapp:detail' book.id%}">{{book.id}}-{{book.name}}</a><br>
    {%endfor%}
    {%endblock%}